# Generated by Django 3.2.9 on 2021-12-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0002_participant_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Group.group'),
        ),
    ]
