# Generated by Django 3.2.9 on 2021-12-09 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0003_alter_participant_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='owner',
        ),
    ]
