# Generated by Django 3.2.9 on 2021-12-12 09:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0004_auto_20211212_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='5qk9bqjtrwktmyf', max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
