# Generated by Django 3.2.9 on 2021-12-15 05:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0011_alter_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='py6n8wh6djkqbrw', max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
