# Generated by Django 3.2.9 on 2021-12-15 06:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0016_alter_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='u13p5lnz9bq69ru', max_length=15, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
