# Generated by Django 3.2.9 on 2021-12-19 10:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Group', '0022_alter_group_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='link',
            field=models.CharField(default='odwz9z2qtfedtxl', max_length=15, unique=True, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
