# Generated by Django 3.2.9 on 2021-12-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0003_auto_20211207_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='ProfilePhoto'),
        ),
    ]
