# Generated by Django 3.2.9 on 2021-12-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0004_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(null=True, upload_to='ProfilePhoto'),
        ),
    ]
